spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
    
server:
  port: 8080
  
#management endpoints on a separate port
management:
  port: 8081
  security:
    enabled: false # management port is internal only. no need to secure it.

logging:
  file: boot_example.log
  org.hibernate: INFO